config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get '/events/pictures',          to: 'events#pictures' #this is soley for testing purposes, i need to be able to view the pictures pages without reaching through a event to do so
  resources :events, :activities, :users
  resources :votes, only: [:index, :create, :new]
  resources :sessions, only: [:new, :create, :destroy]
  resources :trips, only: [:create]
  resources :photos, :only => [:create]

  get '/search',                  to: 'activities#search'
  get '/auth/:provider/callback', to: 'authentications#create'
  get '/events/:id/presentation', to: 'events#presentation'
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :photo, UserPhotoUploader
  has_secure_password
  validates_presence_of :password, :on => :create
  has_many :votes
  has_many :activities, through: :votes
  has_many :authentications
  has_many :trips
  has_many :events, through: :trips
  has_many :photos
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      UserMailer.welcome_email(@user).deliver
      redirect_to activities_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  def edit
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :email, :photo, :motto, :password, :professional_blurb)
    end

end

app/views/users/_new.html.erb
<%= form_for :user, url: users_path, html: {class: "form"} do |f| %>

  <ul class="zero list-unstyled">
    <li>
      <div class="form-header">
        Sign Up
      </div>
    </li>
    <li>
      <p class="form-label">
        First Name
      </p>
      <div class="form-input">
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Last Name
      </p>
      <div class="form-input">
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Username
      </p>
      <div class="form-input">
        <%= f.text_field :username, class: "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Password
      </p>
      <div class="form-input">
        <%= f.password_field :password, class: "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Email
      </p>
      <div class="form-input">
        <%= f.email_field :email, class: "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Motto
      </p>
      <div class="form-input">
        <%= f.text_field :motto, class: "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Picture URL
      </p>
      <div class="form-input">
        <%= f.text_field :picture_url, class: "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Professional Blurb
      </p>
      <div class="form-input">
        <%= f.text_field :professional_blurb, class: "form-control" %>
      </div>
    </li>
    <li>
      <%= f.submit "Sign Up!", :class => "btn-old btn-green form-submit" %>
    </li>

  <% end %>

app/views/users/_new_user.html.erb
<%= form_for :user, url: users_path, html: {class: "form"} do |f| %>

  <ul class="zero list-unstyled">
    <li>
      <div class="form-header">
        Sign Up

      </div>
    </li>
    <li>
      <p class="form-label">
        First Name
      </p>
      <div class="form-input">
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Last Name
      </p>
      <div class="form-input">
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Username
      </p>
      <div class="form-input">
        <%= f.text_field :username, class: "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Password
      </p>
      <div class="form-input">
        <%= f.password_field :password, class: "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Email
      </p>
      <div class="form-input">
        <%= f.email_field :email, class: "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Motto
      </p>
      <div class="form-input">
        <%= f.text_field :motto, class: "form-control" %>
      </div>
    </li>
    <li class="form-input-photo">
      <p class="form-label">
        Photo
      </p>
      <div class="form-input">
        <%= f.file_field :photo, :class=>"form-input" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Professional Blurb
      </p>
      <div class="form-input">
        <%= f.text_field :professional_blurb, class: "form-control" %>
      </div>
    </li>
    <li>
      <%= f.submit "Sign Up!", :class => "btn-old btn-green form-submit" %>
    </li>

  <% end %>

app/views/users/edit.html.erb
<div class="form-wrapper">
<%= form_for @user, html: {:class=> "form"} do |f| %>

  <ul class="zero list-unstyled">
    <li>
      <div class="form-header">
        The Basics
      </div>
    </li>
    <li>
      <p class="form-label">
        Name
      </p>
      <div class="form-input-half-first">
        <%= f.text_field :first_name, :class=> "form-control" %>
      </div>
      <div class="form-input-half-second">
        <%= f.text_field :last_name, :class=> "form-control" %>
      </div>
    </li>
    <li class="form-input-photo">
      <p class="form-label">
        Photo
      </p>
      <div class="form-input">
        <%= f.file_field :photo, :class=>"form-input" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Username
      </p>
      <div class="form-input">
        <%= f.text_field :username, :class=> "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Email
      </p>
      <div class="form-input">
        <%= f.email_field :email, :class=> "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Motto
      </p>
      <div class="form-input">
        <%= f.text_field :motto, :class=> "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Professional Blurb
      </p>
      <div class="form-input">
        <%= f.text_field :professional_blurb, :class=> "form-control" %>
      </div>
    </li>
    <li>
      <%= f.submit "Sign Up!", :class => "btn-old btn-green form-submit" %>
    </li>
  <% end %>
</div>

app/views/users/index.html.erb
<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Username</th>
    <th>Email</th>
    <th>Picture URL</th>
    <th>Professional Blurb</th>
    <th>Motto</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.username %></td>
    <td><%= user.password %></td>
    <td><%= user.email %></td>
    <td><%= user.photo %></td>
    <td><%= user.professional_blurb %></td>
    <td><%= user.motto %></td>
    <td><%= link_to 'Show', user_path(user) %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user_path(user), method: :delete, data: {confirm: 'Are you sure?' } %></td>
  </tr>

<% end %>
</table>
<%= link_to 'New User', new_user_path%>

app/views/users/new.html.erb
<div class="form-wrapper">
<%= form_for :user, url: users_path, html: {class: "form"} do |f| %>
  <ul class="zero list-unstyled">
    <li>
      <div class="form-header">
        Sign Up
        <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited
            this article from being saved:</h2>
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
        <% end %>
      </div>
    </li>
    <li>
      <p class="form-label">
        First Name
      </p>
      <div class="form-input">
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Last Name
      </p>
      <div class="form-input">
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Username
      </p>
      <div class="form-input">
        <%= f.text_field :username, class: "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Password
      </p>
      <div class="form-input">
        <%= f.password_field :password, class: "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Email
      </p>
      <div class="form-input">
        <%= f.email_field :email, class: "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Motto
      </p>
      <div class="form-input">
        <%= f.text_field :motto, class: "form-control" %>
      </div>
    </li>
    <li class="form-input-photo">
      <p class="form-label">
        Photo
      </p>
      <div class="form-input">
        <%= f.file_field :photo, :class=>"form-input" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Professional Blurb
      </p>
      <div class="form-input">
        <%= f.text_field :professional_blurb, class: "form-control" %>
      </div>
    </li>
    <li>
      <%= f.submit "Sign Up!", :class => "btn-old btn-green form-submit" %>
    </li>

  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">

<!-- FB LOGIN -->

  <%= link_to "/auth/facebook", id: "sign_in", type: "button", :class => "btn-facebook-style"  do %>
    <em class="facebook-icon"></em><span>Sign up with Facebook</span>
  <% end %>
  <div class="activities-userProfilePhoto" >
    <%= link_to image_tag(current_user.photo_url(:profile_settings_thumb).to_s, :class => "activities-userProfileImg"), user_path(current_user) %>
  </div>
<!-- FB LOGIN -->

<div class="activities-listWrapper">
  <div class="row activities-activitiesListHeader">
    <h1 id='activity-heading'>
      <%= @user.first_name + " " + @user.last_name %>
    </h1>
  </div>
  <br>
  <ul class="list-unstyled" id="profile-list-padding">
    <li>Email: <i><%= @user.email %></i></li>
    <li>Username: <i><%= @user.username %></i></li>
    <li>Motto: <i><%= @user.motto %></i></li>
    <li>Professional Blurb: <i><%= @user.professional_blurb %></i></li>
  </ul>
</div>
</div>