config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get '/events/pictures',          to: 'events#pictures' #this is soley for testing purposes, i need to be able to view the pictures pages without reaching through a event to do so
  resources :events, :activities, :users
  resources :votes, only: [:index, :create, :new]
  resources :sessions, only: [:new, :create, :destroy]
  resources :trips, only: [:create]
  resources :photos, :only => [:create]

  get '/search',                  to: 'activities#search'
  get '/auth/:provider/callback', to: 'authentications#create'
  get '/events/:id/presentation', to: 'events#presentation'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :activity
  has_many   :trips
  has_many   :photos
  has_many   :users, through: :trips
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @photo = Photo.new
    @events = Event.all
    render layout: 'profile_layout'
  end

  def new
    @event = Event.new
  end

  def pictures
    #this is hardcoded in to allow testing of the view before s3 photo uploading is hooked up for event photos. it will after the fact pull photo urls from the photo table and pass them to the view
    @activities = Activity.all
    @event = Event.first
    @photo = Photo.first
    @photos = Photo.all.includes(:user)
    render :pictures
  end

  def presentation
    @activities = Activity.all
    @event      = Event.find(params[:id])
    @photos     = Photo.all.includes(:user)
    render :presentation
  end

  def show
    @photo = Photo.new
    @event = Event.find(params[:id])
    @users = User.all
    @photo = Photo.new
    @trips = Trip.where(event_id: @event.id)
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
    @event.users << current_user
    if @event.save
      redirect_to @event
    else
      render :new
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:notice] = 'Event Updated!'
      redirect_to @event
    else
      render :edit
    end
  end

  private
    def event_params
      params.require(:event).permit(:date, :start_time, :duration, :activity_id)
    end
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <div class="form-inputs">
    <div class="field">
      <%= f.label :date %>
      <%= f.text_field :date %>
    </div>
    <div class="field">
      <%= f.label :start_time %>
      <%= f.text_field :start_time %>
    </div>
    <div class="field">
      <%= f.label :duration %>
      <%= f.text_field :duration %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit "submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%= render 'events/form' %>

app/views/events/index.html.erb
   <script  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAFV3xWimhcZMCsIXOLZbB6fVmAQfkelFM"></script>

    <script>
      var geocoder;
      var map;

      function initialize() {
        geocoder = new google.maps.Geocoder();
        var mapCanvas = document.getElementById('map_canvas');
        myLatlng = new google.maps.LatLng(   <script  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAFV3xWimhcZMCsIXOLZbB6fVmAQfkelFM"></script>
    <script>
      var geocoder;
      var map;
      var  myLatlng1 = new google.maps.LatLng(37.7582, -122.4415);
      var  myLatlng2 = new google.maps.LatLng(37.7980, -122.4079);
      var  myLatlng3 = new google.maps.LatLng(37.8018, -122.4690);
      var  myLatlng4 = new google.maps.LatLng(37.7701, -122.4721);
      var  myLatlng5 = new google.maps.LatLng(37.7834, -122.4421);
      var  myLatlng6 = new google.maps.LatLng(37.746244, -122.470436);
      var  myLatlng7 = new google.maps.LatLng(37.765787, -122.511978);
      var  myLatlng8 = new google.maps.LatLng(37.825086, -122.421856);
      var  myLatlng9 = new google.maps.LatLng(37.824002, -122.370872);
      var  myLatlng10 = new google.maps.LatLng(37.725087, -122.371387);
      var  myLatlng11 = new google.maps.LatLng(37.746244, -122.422714);

      function initialize() {
        geocoder = new google.maps.Geocoder();
        var mapCanvas = document.getElementById('map_canvas');
        myLatlng = new google.maps.LatLng(37.7582, -122.4415);
        var mapOptions = {
          center: myLatlng,
          zoom: 13
        }
        map = new google.maps.Map(mapCanvas, mapOptions);

      contentString = '<h4><a href="/events/pictures"><%= @events.first.activity.title %><br/></a>Category: <%=@events.first.activity.category%></h4><p><%= @events.first.activity.description %></p><p>Happened on: <%= @events.first.date %></p>'
      var infowindow = new google.maps.InfoWindow({
        content: contentString,
        maxWidth: 150
      });
        function createMarker(pos) {
            var marker = new google.maps.Marker({
              map: map,
              position: pos,
              icon: '../assets/beer_icon2.png',
              url: '/events/pictures',
              draggable: true,
              animation: google.maps.Animation.DROP,
            });
            google.maps.event.addListener(marker, 'click', function() {
                infowindow.open(map,marker);
               //window.location.href = marker.url;
            });
            return marker;
        }
        createMarker(myLatlng1);
        createMarker(myLatlng2);
        createMarker(myLatlng3);
        createMarker(myLatlng4);
        createMarker(myLatlng5);
        createMarker(myLatlng6);
        createMarker(myLatlng7);
        createMarker(myLatlng8);
        createMarker(myLatlng9);
        createMarker(myLatlng10);
        createMarker(myLatlng11);
      }

      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
    <div id='map_canvas'></div> -122.4167);

    </script>
    <div id='map_canvas'></div>

app/views/events/new.html.erb
<%= render 'events/form' %>

app/views/events/pictures.html.erb
   

<div id="jmpress">

  <div class="step" data-x="-800" data-y="20" data-rotate="0" data-z="" data-scale="0" style="height:500px;">
  
    <div class="start-pressy-line"></div>
    <div class="start-pressy" >
      <span>
       Start!
      </span>
    </div>
    <div class="pressy-date">
      <%= @event.date %>
    </div>
    <div class="pressy-title">
      <%= link_to @event.activity.title, event_path(@event) %>
    </div>

  </div>


  <% @photos.each_with_index do |photo, index| %>
  <% index % 4 == 0 ? line_id = "1" : %>
  <% index % 4 == 1 ? line_id = "2" : %>
  <% index % 4 == 2 ? line_id = "3" : %>
  <% index % 4 == 3 ? line_id = "4" : %>

  <% index % 2 == 0 ? vertical_align = 35 : vertical_align = -35 %>

  <% index % 4 == 0  ? vertical_jump = 35 : vertical_jump = -35 %>


    
    <div class="step" id="pic_<%=index%>" data-x="<%= index * 1000 %>" data-y="<%= vertical_align + vertical_jump %>" data-rotate="0" data-z="0" data-scale="0" style="height:500px;">
   
    <div class="photo_wrapper">
    <%= image_tag photo.photo_url_url(:event_photo_500).to_s %>
    </div>

    <div class="curve<%= line_id %> target">
    </div>

      <div class="owners_photo">
        <%= image_tag photo.user.photo_url(:event_presentation_thumb).to_s %>
      </div>

    </div>

   <% if index + 1 == @photos.length %>
     <div class="step" data-x="<%= index * 1000 %>" data-y="0" data-rotate="0" data-z="" data-scale="0" style="height:500px;">

      <div class="end-pressy-line"></div>
        <div class="end-pressy" >
          <span>
           End!
          </span>
        </div>
     </div>
  <% end %> 

 <% end %>


</div>

app/views/events/presentation.html.erb
<div id="jmpress">

  <div class="step" data-x="-800" data-y="20" data-rotate="0" data-z="" data-scale="0" style="height:500px;">
  
    <div class="start-pressy-line"></div>
    <div class="start-pressy" >
      <span>
       Start!
      </span>
    </div>
    <div class="pressy-date">
      <%= @event.date %>
    </div>
    <div class="pressy-title">
      <%= link_to @event.activity.title, event_path(@event) %>
    </div>

  </div>


  <% @photos.each_with_index do |photo, index| %>
  <% index % 4 == 0 ? line_id = "1" : %>
  <% index % 4 == 1 ? line_id = "2" : %>
  <% index % 4 == 2 ? line_id = "3" : %>
  <% index % 4 == 3 ? line_id = "4" : %>

  <% index % 2 == 0 ? vertical_align = 35 : vertical_align = -35 %>

  <% index % 4 == 0  ? vertical_jump = 35 : vertical_jump = -35 %>


    
    <div class="step" id="pic_<%=index%>" data-x="<%= index * 1000 %>" data-y="<%= vertical_align + vertical_jump %>" data-rotate="0" data-z="0" data-scale="0" style="height:500px;">
   
    <div class="photo_wrapper">
    <%= image_tag photo.photo_url_url(:event_photo_500).to_s %>
    </div>

    <div class="curve<%= line_id %> target">
    </div>

      <div class="owners_photo">
        <%= image_tag photo.user.photo_url(:event_presentation_thumb).to_s %>
      </div>

    </div>

   <% if index + 1 == @photos.length %>
     <div class="step" data-x="<%= index * 1000 %>" data-y="0" data-rotate="0" data-z="" data-scale="0" style="height:500px;">

      <div class="end-pressy-line"></div>
        <div class="end-pressy" >
          <span>
           End!
          </span>
        </div>
     </div>
  <% end %> 

 <% end %>


</div>

app/views/events/show.html.erb
<div class="container">
<div class="activities-userProfileFixedWrapper">
<div class="activities-userProfileWrapper">
  <div class="activities-userProfilePhoto" >
    <%= link_to image_tag(current_user.photo_url(:profile_settings_thumb).to_s, :class => "activities-userProfileImg"), user_path(current_user) %>
    <div class="activities-userProfileAttsWrapper">

    <div class="activities-userProfileAtts">

      <div class="activities-userAtts">
        <p>Activities</p>
        <h4>8</h4>
      </div>
      <div class="activities-userAtts">
        <p>Remaining Votes</p>
        <h4>3</h4>
      </div>
      <div class="activities-userAtts">
        <p>User Rating</p>
        <h4>110%</h4>
      </div>

    </div>

    <div class="activities-navTabsWrapper">
     <!-- Nav tabs -->
      <ul class="nav nav-pills activities-nav-pills" role="tablist">
        <li class="active">
          <a href="#accepted" role="tab" data-toggle="tab" class="activities-btn-tabs events-btn-tabs">
            Attending
          </a>
        </li>
        <li>
          <a href="#invited" role="tab" data-toggle="tab" class="activities-btn-tabs events-btn-tabs">
            Invited
          </a>
        </li>
        <li>
          <% if @event.users.include?(current_user) %>
            <div class="events-acceptedInvite"> Accepted </div>
          <% else %>
            <%= link_to "Accept Invite", {
             controller: "trips",
             action:     "create",
             event_id:   @event.id
             }, method: :post,
             :class => "btn-old btn-green events-btn-tabs-accept"
            %>
          <% end %>

        </li>

      </ul>
     <!-- Tab panes -->
      <div class="tab-content activities-tab-content">

        <div class="tab-pane fade in active" id="accepted">
          <ul class="list-unstyled activities-miniList">
            <div id="scroll-eventAccepted" class="wrapper">
              <div> <!-- ScrollBar -->
                <% @event.users.distinct.each do |user| %>
                <li>
                  <%= image_tag user.photo_url(:logged_in_thumb).to_s, :class=> "activities-listPhoto activities-miniListPhoto" %>
                  <%= user.first_name %> <%= user.last_name %>
                  <div class="activities-miniBackersWrapper text-center">
                    <span><%= user.activities.count %></span><br/>
                    votes
                  </div>
                </li>
              <% end %>
            </div><!-- ScrollBar -->
           </div> <!-- ScrollBar -->
          </ul>
        </div>

        <div class="tab-pane fade" id="invited">
        <% activities = current_user.activities %>
            <ul class="list-unstyled activities-miniList">
             <div id="scroll-eventInvited" class="wrapper">
               <div> <!-- ScrollBar -->
                <% @users.each do |user| %>
                    <li>
                      <%= image_tag user.photo_url(:logged_in_thumb).to_s, :class=> "activities-listPhoto activities-miniListPhoto" %>
                      <%= user.first_name %><%= user.last_name %>
                      <div class="activities-miniBackersWrapper text-center">
                        <span><%= user.activities.count %></span><br/>
                        votes
                      </div>
                    </li>
                <% end %>
              </div><!-- end scroll-myVotes -->
            </div><!-- end scroll-myVotes -->
          </ul>
        </div>
      </div><!-- End Tab Panes -->

      </div> <!-- end NavTabs Wrapper -->


      </div> <!-- end NavTabs Wrapper -->

    </div><!-- end activities-userProfileAttsWrapper -->
  </div><!-- end activities-userProfilePhoto -->
</div><!--  end activities-userProfileWrapper -->
</div><!-- end activities-userProfileFixedWrapper -->

<div class="event-winnerWrapper">
  <div class="text-center">
    <h3>
      <span>Winning Event:</span>
      Lets go <%= @event.activity.title %>!!
    </h3>
  </div>
</div><!-- end event-Wrapper -->

<div class="event-Wrapper">
  <div class="center">
    <%= image_tag @event.activity.photo_url(:profile).to_s, :style => "border-radius:5px; width: 100%; height:250px;"%>
  </div>
</div><!-- end event-Wrapper -->

<div class="event-Wrapper">
  <div class="event-Header center">
    <ul class="list-unstyled zero">
      <li>
        <p class="event-Label">
          Title:
        </p>
        <p class="event-Content">
          <%= @event.activity.title %>
        </p>
      </li>
      <li>
        <p class="event-Label">
          Deets:
        </p>
        <p class="event-Content">
          <%= @event.activity.description %>
        </p>
      </li>
      <li>
        <p class="event-Label">
          Necessities:
        </p>
        <p class="event-Content">
          <%= @event.activity.necessities %>
        </p>
      </li>
      <li>
        <p class="event-Label">
          Date:
        </p>
        <p class="event-Content">
          <%= @event.date %>
        </p>
      </li>
      <li>
        <p class="event-Label">
          Time:
        </p>
        <p class="event-Content">
          <%= @event.start_time %>
        </p>
       <li>
        <p class="event-Label">
          Duration:
        </p>
        <p class="event-Content">
          <%= @event.duration %>
        </p>
      </li>
      <li>
        <p class="event-Label">
          Location:
        </p>
        <p class="event-Content">
          <%= @event.activity.location %>
        </p>
      </li>
      <li>
        <p class="event-Label">
          Upload Your Photos!
        </p>
        <p class="event-Content">
          <%= form_for @photo do |f| %>
            <%= f.file_field :photo_url %>
            <%= f.hidden_field :event_id, value: @event.id %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.submit 'Upload Photo!', :class => "events-photoUpload btn-old btn-green" %>
          <% end %>
        </p>
      </li>
    </ul>
  </div>
</div><!-- end event-Wrapper -->

<div class="event-Wrapper">
  <div class="center">
    <!--google Map -->
   <script  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAFV3xWimhcZMCsIXOLZbB6fVmAQfkelFM"></script>
    <script>
      var geocoder;
      var map;

      function initialize() {
        geocoder = new google.maps.Geocoder();
        var mapCanvas = document.getElementById('map_canvas');
        myLatlng = new google.maps.LatLng(37.7833, -122.4167);
        var mapOptions = {
          center: myLatlng,
          zoom: 12
        }
        map = new google.maps.Map(mapCanvas, mapOptions)
        codeAddress();
      }
      function codeAddress() {
        geocoder.geocode( { 'address': '<%= @event.activity.location %>'}, function(results, status) {
          if (status == google.maps.GeocoderStatus.OK) {
            map.setCenter(results[0].geometry.location);
            console.log(results[0].geometry.location);
            var iconBase = 'https://maps.google.com/mapfiles/kml/shapes/';
            var marker = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location,
                icon: iconBase + 'info-i_maps.png'
            });
          }
        });
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
    <div id='map_canvas'></div>

    <!--End of Google Map-->
  </div>
</div><!-- end event-Wrapper -->