config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get '/events/pictures',          to: 'events#pictures' #this is soley for testing purposes, i need to be able to view the pictures pages without reaching through a event to do so
  resources :events, :activities, :users
  resources :votes, only: [:index, :create, :new]
  resources :sessions, only: [:new, :create, :destroy]
  resources :trips, only: [:create]
  resources :photos, :only => [:create]

  get '/search',                  to: 'activities#search'
  get '/auth/:provider/callback', to: 'authentications#create'
  get '/events/:id/presentation', to: 'events#presentation'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  mount_uploader :photo, ActivityPhotoUploader
  belongs_to :user
  belongs_to :event
  has_many   :votes
  has_many   :events
  has_many   :users, through: :votes
  validates  :title, presence: true
  validates  :description, presence: true
  validates  :location, presence: true
  validates  :category, presence: true

  def self.sort_acrtivities( activities )
    list = []
    activities.each do |act|
      list << act.votes.count
    end

    return activities if list.size <= 1 # already sorted
    swapped = true
    while swapped do
      swapped = false
      0.upto(list.size-2) do |i|
        if list[i] < list[i+1]
          list[i], list[i+1] = list[i+1], list[i] # swap values
          activities[i], activities[i+1] = activities[i+1], activities[i] # swap values
          swapped = true
        end
      end
    end

    activities
  end
end

app/controllers/activities_controller.rb
require 'date'
class ActivitiesController < ApplicationController
  before_filter :corresponding_day_page, :only => :index
  before_filter :sort_by_vote_count, :only => [:index, :create, :search]

  def index
    @activities = Activity.all
    @activity   = Activity.new
    @vote       = Vote.new
    # @search_activities = true

    @sorted_by_vote = Activity.sort_acrtivities(@activities)
      today = (Time.now.midnight..Time.now)
    @recent_activities = Activity.where(created_at: today)
    @trending_activities = Activity.where(created_at: today)
    @trending_activities = Activity.sort_acrtivities(@trending_activities)

    render :index
  end

  def show
    @activities = Activity.all
    @activity = Activity.find(params[:id])
  end

  def new
    @activity = Activity.new
  end

  def create
    @vote       = Vote.new
    @activities = Activity.all
    @activity   = Activity.new(activity_params)
    if @activity.save
      @sorted_by_vote = Activity.sort_acrtivities(@activities)
      week = ((Time.now-604800)..Time.now)
      today = (Time.now.midnight..Time.now)
      @trending_activities = Activity.where(created_at: week)
      @recent_activities = Activity.where(created_at: today)
      @trending_activities = Activity.sort_acrtivities(@trending_activities)
      redirect_to activities_path
    else
      render :new
    end
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])

    if @activity.update(activity_params)
      redirect_to activities_path
    else
      render :edit
    end
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to activities_path
  end

  def search
   @activities = Activity.where(category: params[:query].downcase)
     today = (Time.now.midnight..Time.now)
     if @activities.count > 1
       @sorted_by_vote = Activity.sort_acrtivities(@activities)
       @trending_activities = @activities.where(created_at: today)
       @trending_activities = Activity.sort_acrtivities(@trending_activities)
     else
       @sorted_by_vote = @activities
       @trending_activities = @activities
     end

     @recent_activities = @activities.where(created_at: today)
     @activity = Activity.new
     @vote = Vote.new
     render :index
  end

  private

    def saturday?
      Date.today.wday == 6
    end

    def friday?
      Date.today.wday == 5
    end

    def activity_params
      params.require(:activity).permit(:title, :description, :location,
        :category, :icon, :photo, :necessities, :user_id)
    end

    def corresponding_day_page
      @event = Event.last
      redirect_to @event if friday?
      redirect_to @event if saturday?
    end

    def sort_by_vote_count
      activities = Activity.all
      @sorted_by_vote = Activity.sort_acrtivities(activities)
    end

end

app/views/activities/_activity_form.html.erb
<%= form_for @activity do |f| %>
  <div class="form">
    <ul class="zero list-unstyled">
      <li>
        <div class="form-header">
            Add An Activity
            <% if @activity.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@activity.errors.count, "error") %> prohibited
                this article from being saved:</h2>
              <ul>
              <% @activity.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
            <% end %>
            </div>
        </div>
      </li>
      <li>
        <p class="form-label">
         Title
        </p>
      <div class="form-input">
        <%= f.text_field :title, :placeholder => "title", :class => "form-control" %>
      </div>
    </li>
    <li class="form-input-photo">
      <p class="form-label">
        Photo
      </p>
      <div class="form-input">
        <%= f.file_field :photo, :class=>"form-input" %>
      </div>
    </li>
    <li>
      <p class="form-label form-label-dropdown">
        Category
      </p>
      <div class="form-input">
        <%= f.select :category, options_for_select([
        ['Biking','biking'],
        ['Climbing','climbing'],
        ['Drinking','drinking'],
        ['Hiking','hiking'],
        ['Kayaking','kayaking'],
        ['Paddleboarding','paddleboarding'],
        ['Sailing','sailing'],
        ['Surfing','surfing'],
        ['Other','other']]), :class=>"form-input" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Description
      </p>
      <div class="form-input">
        <%= f.text_area :description, :placeholder => "description", :class => "form-control"  %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Address
      </p>
      <div class="form-input">
        <%= f.text_field :location, :placeholder => "Address", :class => "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Necessities
      </p>
      <div class="form-input">
        <%= f.text_field :necessities, :placeholder => "necessities", :class => "form-control" %>
      </div>
    </li>
    <li>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.submit 'Submit Activity', :class => "btn-old btn-green form-submit" %>
    </li>
   </ul> <!-- End of ul -->
  </div> <!-- End of Form Type -->
<% end %>

app/views/activities/_activity_modal_form.html.erb
<%= form_for @activity do |f| %>
  <div class="form">
    <ul class="zero list-unstyled">
      <li>
        <div class="form-header">
            Add An Activity
        </div>
        <% if @activity.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@activity.errors.count, "error") %> prohibited
            this article from being saved:</h2>
          <ul>
          <% @activity.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
        <% end %>
      </li>
      <li>
        <p class="form-label">
         Title
        </p>
      <div class="form-input">
        <%= f.text_field :title, :placeholder => "title", :class => "form-control" %>
      </div>
    </li>
    <li class="form-input-photo">
      <p class="form-label">
        Photo
      </p>
      <div class="form-input">
        <%= f.file_field :photo, :class=>"form-input" %>
      </div>
    </li>
    <li>
      <p class="form-label form-label-dropdown">
        Category
      </p>
      <div class="form-input">
        <%= f.select :category, options_for_select([
        ['Biking','biking'],
        ['Climbing','climbing'],
        ['Drinking','drinking'],
        ['Hiking','hiking'],
        ['Kayaking','kayaking'],
        ['Paddleboarding','paddleboarding'],
        ['Sailing','sailing'],
        ['Surfing','surfing'],
        ['Other','other']]), :class=>"form-input" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Description
      </p>
      <div class="form-input">
        <%= f.text_area :description, :placeholder => "description", :class => "form-control"  %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Address
      </p>
      <div class="form-input">
        <%= f.text_field :location, :placeholder => "address", :class => "form-control" %>
      </div>
    </li>
    <li>
      <p class="form-label">
        Necessities
      </p>
      <div class="form-input">
        <%= f.text_field :necessities, :placeholder => "necessities", :class => "form-control" %>
      </div>
    </li>
    <li>
      <%= f.hidden_field :user_id, value: current_user.id %>

      <%= f.submit 'Submit Activity', :class => "btn-old btn-green form-submit activities-addActivityModalSubmitBtn" %>
    </li>
   </ul> <!-- End of ul -->
  </div> <!-- End of Form Type -->
<% end %>

app/views/activities/_modal_add_activity.html.erb
<!-- Modal -->
<div class="modal fade" id="addActivityModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog activities-addActivityModalDialog">
    <div class="modal-content activities-addActivityModalContent">
      <div class="modal-body zero">
        <%= render 'activity_modal_form' %>
      </div>
    </div>
  </div>
</div>

app/views/activities/_vote_up.html.erb
<%= form_for @vote do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :activity_id, :value => activity.id %>
  <%= f.button :class => "activities-voteUpButton" do %>
    <i class="fa fa-arrow-circle-o-up fa-3x"></i>
  <% end %>
<% end %>

app/views/activities/edit.html.erb
<div class="form-wrapper">
  <%= render 'activity_form' %> 
</div> 

app/views/activities/gone_fishing.html.erb
why are you out there getting it you lazy SOB?

app/views/activities/index.html.erb
<div class="container">
<div class="activities-userProfileFixedWrapper">
<div class="activities-userProfileWrapper">
  <div class="activities-userProfilePhoto" >
    <%= link_to image_tag(current_user.photo_url(:profile_settings_thumb).to_s, :class => "activities-userProfileImg"), user_path(current_user) %>
    <div class="activities-userProfileAttsWrapper">

    <div class="activities-userProfileAtts">

      <div class="activities-userAtts">
        <p>Activities</p>
        <h4><%= current_user.activities.count %></h4>
      </div>
      <div class="activities-userAtts">
        <p>Remaining Votes</p>
        <h4 id='remaining-votes'><%= current_user.remaining_votes%></h4>
      </div>
      <div class="activities-userAtts">
        <p>User Rating</p>
        <h4>110%</h4>
      </div>

    </div>

    <div class="activities-navTabsWrapper">
     <!-- Nav tabs -->
      <ul class="nav nav-pills activities-nav-pills" role="tablist">
        <li class="active">
          <a href="#home" role="tab" data-toggle="tab" class="activities-btn-tabs">
            My Activities
          </a>
        </li>
        <li>
          <a href="#profile" role="tab" data-toggle="tab" class="activities-btn-tabs">
            Voted Activities
          </a>
        </li>
        <li>
          <%= link_to "Add Activity", "#", :class=> "activities-btn-tabs btn-old btn-green", 'data-toggle'=>"modal", 'data-target'=>"#addActivityModal" %>
        </li>

      </ul>
     <!-- Tab panes -->
      <div class="tab-content activities-tab-content">

        <div class="tab-pane fade active in" id="home">
          <% activities = @activities.where(user_id: current_user.id) %>
          <ul class="list-unstyled activities-miniList">
            <div id="scroll-myActivities" class="wrapper">
              <div> <!-- ScrollBar -->
                <% activities.distinct.each do |activity| %>
                <li>
                  <%= image_tag activity.photo_url(:mini_activity_list_thumb).to_s, :class=> "activities-listPhoto activities-miniListPhoto" %>
                  <%= activity.title %>
                  <div class="activities-miniBackersWrapper text-center">
                    <span><%= activity.votes.count %></span><br/>
                    votes
                  </div>
                </li>
              <% end %>
            </div><!-- ScrollBar -->
           </div> <!-- ScrollBar -->
          </ul>
        </div>

        <div class="tab-pane fade" id="profile">
        <% activities = current_user.activities %>
            <ul class="list-unstyled activities-miniList">
             <div id="scroll-myVotes" class="wrapper">
               <div> <!-- ScrollBar -->
                <% activities.distinct.each do |activity| %>
                    <li>
                      <%= image_tag activity.photo_url(:mini_activity_list_thumb).to_s, :class=> "activities-listPhoto activities-miniListPhoto" %>
                      <%= activity.title %>
                      <div class="activities-miniBackersWrapper text-center">
                        <span><%= activity.votes.count %></span><br/>
                        votes
                      </div>
                    </li>
                <% end %>
              </div><!-- end scroll-myVotes -->
            </div><!-- end scroll-myVotes -->
          </ul>
        </div>
      </div>

      </div> <!-- end NavTabs Wrapper -->

    </div>
  </div>
</div>
</div><!-- end activities-userProfileFixedWrapper -->

<div class="activities-listWrapper active"> 

  <div class="row activities-activitiesListHeader">
    <h1 id='activity-heading'>
      Activities
    </h1>

    <div class="activities-countdownWrapper">
      <div id="countdown"></div>
    </div>
  </div>
  <!-- Nav tabs --> 
  <ul class="nav nav-tabs activities-queryHeader" role="tablist" id="votes-tabs">
    <li class>
      <a class="activities-queryItem" href="#recently" role="tab" data-toggle="tab">
        Recently Added
      </a>
    </li>
    <li>
      <a class="activities-queryItem" href="#trending" role="tab" data-toggle="tab">
        Trending
      </a>
    </li>
    <li class="active activities-queryVote">
      <a clas="activities-queryItem"  href="#votes" role="tab" data-toggle="tab">
        Leaderboard
      </a>
    </li>
  </ul>
<div class="tab-content">

<!--  Recent Activities tab -->
  <div class="tab-pane fade" id="recently">
    <ul class="list-unstyled">
      <% @activities.order(created_at: :desc).each do |activity| %>
        <!-- Form For ajax Vote -->
        <%= form_for @vote do |f| %>
          <%= f.hidden_field :user_id, :value => current_user.id %>
          <%= f.hidden_field :activity_id, :value => activity.id %>
          <%= f.button :class=> "activities-listItem" do %>
            <li>
              <%= image_tag activity.photo_url(:activity_list_thumb).to_s, :class=> "activities-listPhoto" %>
              <div id="activities-ArrowUp" class="">
                <%= image_tag "arrow.png" %>
              </div>
              <div class="activities-votesWrapper text-center">
               <span>
                 <%= activity.votes.count %>
               </span>
               <br/>
              </div>
            </li>
          <% end %><!-- END Button-->
        <% end %> <!-- END Form -->
        <!-- Activity Title -->
        <%= link_to activity, :class => "activites-activityTitle" do %>
          <%= activity.title %>
        <% end %>
      <%end%> <!-- END Activity Item (Ruby) -->
    </ul>
  </div>
<!-- END Recent Activities tab -->

<!--  Trending Activities tab -->
  <div class="tab-pane fade" id="trending">
    <ul class="list-unstyled">
      <% @trending_activities.each do |activity| %>

      <!-- Form For ajax Vote -->
      <%= form_for @vote do |f| %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.hidden_field :activity_id, :value => activity.id %>
        <%= f.button :class=> "activities-listItem" do %>
          <li>
            <%= image_tag activity.photo_url(:activity_list_thumb).to_s, :class=> "activities-listPhoto" %>
            <div id="activities-ArrowUp" class="">
              <%= image_tag "arrow.png" %>
            </div>
            <div class="activities-votesWrapper text-center">
             <span>
               <%= activity.votes.count %>
             </span>
             <br/>
            </div>
          </li>
        <% end %><!-- END Button-->
      <% end %> <!-- END Form -->
      <!-- Activity Title -->
      <%= link_to activity, :class => "activites-activityTitle" do %>
        <%= activity.title %>
      <% end %>

      <% end %> <!-- END Activity Item (Ruby) -->
    </ul> 
  </div>
<!-- END Trending Activities tab -->

<!--  Leaderboard Activities tab -->
<div class="tab-pane fade in active" id="votes">       
  <ul class="list-unstyled">
     <% @sorted_by_vote.each do |activity| %>

       <!-- Form For ajax Vote -->
       <%= form_for @vote do |f| %>
         <%= f.hidden_field :user_id, :value => current_user.id %>
         <%= f.hidden_field :activity_id, :value => activity.id %>
         <%= f.button :class=> "activities-listItem" do %>
           <li>
             <%= image_tag activity.photo_url(:activity_list_thumb).to_s, :class=> "activities-listPhoto" %>
             <div id="activities-ArrowUp" class="">
                <%= image_tag "arrow.png" %>
             </div>
             <div class="activities-votesWrapper text-center">
              <span>
                <%= activity.votes.count %>
              </span>
              <br/>
             </div>
           </li>
         <% end %> <!-- END Button-->
       <% end %> <!-- END Form -->
       <!-- Activity Title -->
       <%= link_to activity, :class => "activites-activityTitle" do %>
         <%= activity.title %>
       <% end %>

     <% end %> <!-- END Leaderboard Item (Ruby) -->
  </ul>
</div>
<!-- End Leaderboard Activities Tab -->

</div>

<%= render 'activities/modal_add_activity' %>

app/views/activities/new.html.erb
<div class="form-wrapper">
  <%= render 'activity_modal_form' %>
</div>

app/views/activities/rsvp.html.erb
RSVP you lazy SOB

app/views/activities/scraps.html.erb
<!-- rm unused stuff.... -->
 <!-- <h4>"<%= current_user.motto%>"</h4>
      <h4> My Votes </h4>
      <% current_user.activities.each_with_index do |activity,index| %>
        <p><%= index+1 %>. <%= activity.title %></p>
      <% end %> -->
      <!--   <%= link_to 'Create New Activity', new_activity_path, :class => "btn btn-primary activities-createNewActivity" %>
 -->

app/views/activities/show.html.erb
<div class="container">

<div class="activities-userProfileFixedWrapper">
<div class="activities-userProfileWrapper">
  <div class="activities-userProfilePhoto" >
    <%= link_to image_tag(current_user.photo_url(:profile_settings_thumb).to_s, :class => "activities-userProfileImg"), user_path(current_user) %>
    <div class="activities-userProfileAttsWrapper">

    <div class="activities-userProfileAtts">

      <div class="activities-userAtts">
        <p>Activities</p>
        <h4><%= current_user.activities.count %></h4>
      </div>
      <div class="activities-userAtts">
        <p>Remaining Votes</p>
        <h4 id='remaining-votes'><%= current_user.remaining_votes%></h4>
      </div>
      <div class="activities-userAtts">
        <p>User Rating</p>
        <h4>110%</h4>
      </div>
    </div>

    <div class="activities-navTabsWrapper">
     <!-- Nav tabs -->
      <ul class="nav nav-pills activities-nav-pills" role="tablist">
        <li class="active">
          <a href="#home" role="tab" data-toggle="tab" class="activities-btn-tabs">
            My Activities
          </a>
        </li>
        <li>
          <a href="#profile" role="tab" data-toggle="tab" class="activities-btn-tabs">
            Voted Activities
          </a>
        </li>
        <li>
          <%= link_to "Add Activity", "#", :class=> "activities-btn-tabs btn-old btn-green", 'data-toggle'=>"modal", 'data-target'=>"#addActivityModal" %>
        </li>
      </ul>
     <!-- Tab panes -->
      <div class="tab-content activities-tab-content">

        <div class="tab-pane fade in active" id="home">
          <% activities = @activities.where(user_id: current_user.id) %>
          <ul class="list-unstyled activities-miniList">
            <div id="scroll-myActivities" class="wrapper">
              <div> <!-- ScrollBar -->
                <% activities.each do |activity| %>
                <li>
                  <%= image_tag activity.photo_url(:mini_activity_list_thumb).to_s, :class=> "activities-listPhoto activities-miniListPhoto" %>
                  <%= activity.title %>
                  <div class="activities-miniBackersWrapper text-center">
                    <span><%= activity.votes.count %></span><br/>
                    votes
                  </div>
                </li>
              <% end %>
            </div><!-- ScrollBar -->
           </div> <!-- ScrollBar -->
          </ul>
        </div>

        <div class="tab-pane fade" id="profile">
        <% activities = current_user.activities %>
            <ul class="list-unstyled activities-miniList">
             <div id="scroll-myVotes" class="wrapper">
               <div> <!-- ScrollBar -->
                <% activities.each do |activity| %>
                    <li>
                      <%= image_tag activity.photo_url(:mini_activity_list_thumb).to_s, :class=> "activities-listPhoto activities-miniListPhoto" %>
                      <%= activity.title %>
                      <div class="activities-miniBackersWrapper text-center">
                        <span><%= activity.votes.count %></span><br/>
                        votes
                      </div>
                    </li>
                <% end %>
              </div><!-- end scroll-myVotes -->
            </div><!-- end scroll-myVotes -->
          </ul>
        </div>
      </div>

      </div> <!-- end NavTabs Wrapper -->

    </div>
  </div>
</div>
</div><!-- end activities-userProfileFixedWrapper -->


<!-- Activity Main Section -->
<div class="event-winnerWrapper">
  <div class="text-center">
    <h3>
      <span>Activity Details:</span>
      Lets go <%= @activity.title %>!!
    </h3>
  </div>
</div><!-- end event-Wrapper -->

<div class="event-Wrapper">
  <div class="center">
    <!-- Add stock activity photo -->
    <%= image_tag @activity.photo_url(:profile).to_s, :style => "border-radius:5px; width: 100%; height:250px;" %>
  </div>
</div><!-- end event-Wrapper -->

<div class="event-Wrapper">
  <div class="event-Header center">
    <ul class="list-unstyled zero">
      <li>
        <p class="event-Label">
          Title:
        </p>
        <p class="event-Content">
          <%= @activity.title %>
        </p>
      </li>
      <li>
        <p class="event-Label">
          Description:
        </p>
        <p class="event-Content">
          <%= @activity.description %>
        </p>
      </li>
      <li>
        <p class="event-Label">
          Address:
        </p>
        <p class="event-Content">
          <%= @activity.location %>
        </p>
      </li>
      <li>
        <p class="event-Label">
          Category:
        </p>
        <p class="event-Content">
          <%= @activity.category %>
        </p>
      </li>
      <li>
        <p class="event-Label">
          Necessities:
        </p>
        <p class="event-Content">
          <%= @activity.necessities %>
        </p>
      </li>
      <li>
    </ul>
  </div>
</div><!-- end event-Wrapper -->

<div class="event-Wrapper">
  <div class="center">

    <!--google Map -->
   <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script>
      var geocoder;
      var map;

      function initialize() {
        geocoder = new google.maps.Geocoder();
        var mapCanvas = document.getElementById('map_canvas');
        myLatlng = new google.maps.LatLng(37.7833, -122.4167);
        var mapOptions = {
          center: myLatlng,
          zoom: 12
        }
        map = new google.maps.Map(mapCanvas, mapOptions)
        codeAddress();
      }
      function codeAddress() {
        geocoder.geocode( { 'address': '<%= @activity.location %>'}, function(results, status) {
          if (status == google.maps.GeocoderStatus.OK) {
            map.setCenter(results[0].geometry.location);
            console.log(results[0].geometry.location);
            var marker = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location
            });
          }
        });
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
    <div id='map_canvas'></div>

    <!--End of Google Map-->
  </div>

  <!-- Nav Tabs -->
   <ul class="nav nav-pills activities-nav-pills" role="tablist">
    <li>
    <%= link_to 'See All Activities', activities_path %>
    </li>
    <li>
    <%= link_to 'Edit Activity', edit_activity_path %>
    </li>
    <li>
    <%= link_to 'Delete Activity', activity_path, method: :delete %>
    </li>
  </ul>

</div><!-- end event-Wrapper -->
<!-- Modal -->
<div class="modal fade" id="addActivityModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog activities-addActivityModalDialog">
    <div class="modal-content activities-addActivityModalContent">
      <div class="modal-body zero">
        <%= render 'activity_modal_form' %>
      </div>
    </div>
  </div>
</div>