config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get '/events/pictures',          to: 'events#pictures' #this is soley for testing purposes, i need to be able to view the pictures pages without reaching through a event to do so
  resources :events, :activities, :users
  resources :votes, only: [:index, :create, :new]
  resources :sessions, only: [:new, :create, :destroy]
  resources :trips, only: [:create]
  resources :photos, :only => [:create]

  get '/search',                  to: 'activities#search'
  get '/auth/:provider/callback', to: 'authentications#create'
  get '/events/:id/presentation', to: 'events#presentation'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
   <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

  <title><%= content_for?(:title) ? yield(:title) : "Live It Up Social" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href='http://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>

  <%= csrf_meta_tags %>
  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
 <body>
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Live It Up <span>Social</span></a>
      </div>
      <div class="collapse navbar-collapse">


      <% if @search_activities == true %>
        <form id="activities-search", action='/search'>
          <label>
              <class="fa fa-search"> </i>
            <input  id ='activities-search-input'type="text" name="query" class="form-control" placeholder="search activities">
          </label>
        </form>
      <% end %>

        <ul class="nav navbar-nav pull-right">
          <li >
            <%= link_to "Past Events", events_path %>
          </li>
          <li>
            <%= link_to "Votable Activities", activities_path %>
          </li>
            <% unless current_user.nil? %>
          <li>
               <div class="dropdown">
                <button class="btn-dropdown dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
                <%= link_to image_tag(current_user.photo_url(:logged_in_thumb).to_s, :class => "app-userMiniProfileImg"), activities_path %>
                <%= current_user.first_name %>
                </button>
                  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                    <li role="presentation">

                        <%= link_to 'Profile', user_path(current_user) %>
                    </li>
                    <li role="presentation">
                        <%= link_to 'Log out', session_path(current_user), method: :delete%>

                    </li>
                  </ul>
                </div>
          </li>
          <% else %>
            <li>
              <%= link_to "Log In", '#', 'data-toggle'=>"modal", 'data-target'=>"#loginModal" %>
            </li>
            <li>
              <%= link_to "Sign Up", '#', 'data-toggle' => "modal",  'data-target'=>'#signupModal' %>
            </li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
  <div class="container main-container">
  <%= yield %>
  </div><!-- /.container -->
</body>
</html>

app/views/layouts/home_layout.html.erb
<!DOCTYPE html>
<html lang="en">
   <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

  <title><%= content_for?(:title) ? yield(:title) : "Live It Up Social" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>

  <%= csrf_meta_tags %>
  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="display: none;">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Live It Up <span>Social</span></a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav pull-right">
          <li >
            <a href="#">
                Past Events
            </a>
          </li>
          <li>
            <%= link_to "Votable Activities", activities_path %>
          </li>
            <% unless current_user.nil? %>
          <li>
               <div class="dropdown">
                <button class="btn-dropdown dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
                <%= link_to image_tag(current_user.photo_url(:logged_in_thumb).to_s, :class => "app-userMiniProfileImg"), activities_path %>
                <%= current_user.first_name %>
                </button>
                  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                    <li role="presentation">

                        <%= link_to 'Profile', user_path(current_user) %>
                    </li>
                    <li role="presentation">
                        <%= link_to 'Log out', session_path(current_user), method: :delete%>

                    </li>
                  </ul>
                </div>
          </li>
          <% else %>
          <li>
            <%= link_to "Log In", '#', 'data-toggle'=>"modal", 'data-target'=>"#loginModal" %>
          </li>
          <li>
            <%= link_to "Sign Up", '#', 'data-toggle' => "modal",  'data-target'=>'#signupModal' %>
          </li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </nav>
<section id="homepage_body">
  <div class="container main-container">
    <div id="main_background">


      <div class="home-titleWrapper">
        <h3 class="homepage_title">Time until our next event: </h3>
        <div id="saturday_countdown" class="countdown-home"></div>
        <h3 class="homepage_title homepage_text">What are you doing this weekend?</h3>
      </div>
    </div>
  <%= yield %>
  </div><!-- /.container -->
</section>

<article class="homepage-info">
  <div class="row module content">
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <div class="caption text-center">
          <h3 class="home-info-weight"><span class="fa fa-pencil-square-o fa-color"></span> Sign Up</h3>
          <p>Sign up to see what event we're doing this weekend.</p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <div class="caption text-center">
          <h3 class="home-info-weight"><span class="fa fa-bicycle fa-color"></span> Add an Activity</h3>
          <p>Suggest a new activity or get behind one of our listed ideas.</p>
        </div>
      </div>
     </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <div class="caption text-center">
          <h3 class="home-info-weight"><span class="fa fa-glass fa-color"></span> Have Fun</h3>
          <p>Hike, climb, bike, etc. with us (*etc. often means drinking)!
        </div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <div class="container">
    <div class="pic-title">
      <h1>Check out our past events!</h1>
    </div>
    <div id="pic-polaroid-container">
    <div class="wrap">
      <a href="#" class="polaroid"><%= image_tag "lands_end_2.jpg" %></a>
      <p>Land's End, October 2014</p>
    </div>
    <div class="wrap2">
      <a href="#" class="polaroid"><%= image_tag "cable_car.jpg" %></a>
      <p>Cable Cars, June 2014</p>
    </div>
    <div class="wrap3">
      <a href="#" class="polaroid"><%= image_tag "fort_mason.jpg" %></a>
      <p>Fort Mason, August 2014</p>
    </div>
    <div class="wrap3">
      <a href="#" class="polaroid"><%= image_tag "gg-bridge.jpg" %></a>
      <p>Golden Gate Run, September 2014</p>
    </div>
    <div class="wrap2">
      <a href="#" class="polaroid"><%= image_tag "lands_end_5.jpg" %></a>
      <p>Hiking SF, July 2014</p>
    </div>
    <div class="wrap">
      <a href="#" class="polaroid"><%= image_tag "main_background.jpg" %></a>
      <p>Biking Marin, June 2014</p>
    </div>
    <div class="wrap">
      <a href="#" class="polaroid"><%= image_tag "ocean_beach.jpg" %></a>
      <p>Ocean Beach Surfing, May 2014</p>
    </div>
    <div class="wrap2">
      <a href="#" class="polaroid"><%= image_tag "pier.jpg" %></a>
      <p>SF Waterfront, October 2014</p>
    </div>
    <div class="wrap3">
      <a href="#" class="polaroid"><%= image_tag "lands_end_9.jpg" %></a>
      <p>Drunk Guy, October 2014</p>
    </div>
  </div>
  </div>

  </article>

  <!-- Login Modal -->
  <div class="modal fade custom-login-modal" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog sessions-loginModalDialog">
    <div class="modal-content sessions-loginModalContent">
      <div class="modal-header sessions-loginModalHeader">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
         ×
        </button>
        <p class="modal-title text-center">
         Sign into Live It Up Social
        </p>
      </div>
          <div class="modal-body zero">
            <%= render 'sessions/new' %>
          </div>

        <div class="sessions-loginModalFooter">
         <p>Don't have an account? <a href="/sign_up" class="need-sign-up">Sign up</a></p>
        </div>

    </div>
  </div>
</div>

<!-- Sign Up Modal -->
  <div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog users-signupModalDialog">
    <div class="modal-content users-signupModalContent">
      <div class="modal-body zero">
        <%= render 'users/new_user' %>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/layouts/profile_layout.html.erb
<!DOCTYPE html>
<html lang="en">
   <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

  <title><%= content_for?(:title) ? yield(:title) : "Live It Up Social" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
 <body>
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Live It Up <span>Social</span></a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav pull-right">
          <li >
            <a href="#">
              Past Events
            </a>
          </li>
          <li>
            <%= link_to "Votable Activities", activities_path %>
          </li>
            <% unless current_user.nil? %>
          <li>
               <div class="dropdown">
                <button class="btn-dropdown dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
                <%= link_to image_tag(current_user.photo_url(:logged_in_thumb).to_s, :class => "app-userMiniProfileImg"), activities_path %>             
                <%= current_user.first_name %> 
                </button>
                  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                    <li role="presentation">
                      
                        <%= link_to 'Profile', user_path(current_user) %>
                    </li>
                    <li role="presentation">
                        <%= link_to 'Log out', session_path(current_user), method: :delete%>
                      
                    </li>
                  </ul>
                </div>
          </li>
          <% else %>
          <li>
            <%= link_to "Log In", '#', 'data-toggle'=>"modal", 'data-target'=>"#loginModal" %>
          </li>
          <li>
            <%= link_to "Sign Up", '#', 'data-toggle' => "modal",  'data-target'=>'#signupModal' %>
          </li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>

  <%= yield %>
  <!-- /.container -->

</body>
</html>